replicaCount: 1

app:
  name: rest-flask-application
  image: dockerpratik/rest-flask
  pullPolicy: IfNotPresent
  tag: "v5"

db:
  name: mysql
  image: mysql
  pullPolicy: IfNotPresent
  tag: "5.6"

appService:
  type: NodePort
  port: 8080

PersistentVolume:
  mysql: 
    storageName: mysql-persistent-storage
    pvcName: mysql-pv-claim
