apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name -}}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
